# Generated by Django 6.0.8 on 2026-09-05 21:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rh', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='department',
            name='entreprise_id',
            field=models.CharField(blank=True, db_index=True, default='', max_length=255),
        ),
        migrations.AddField(
            model_name='employee',
            name='entreprise_id',
            field=models.CharField(blank=True, db_index=True, default='', max_length=255),
        ),
    ]
